### ISSUE TITLE
Update UI, make it responsive on multiple devices (mobile/tablet)

### ISSUE THREAD

**Issue by SamirHodzic** [SamirHodzic/ngx-snake#2]

**Comment by thisudoriguy** [comment]
Hey, would love to help. Kindly spill what you want to do

**Comment by SamirHodzic** [comment]
Hey @thisudoriguy, thanks for your interest. As you can see in [app.component.css](https://github.com/SamirHodzic/ngx-snake/blob/master/src/app/app.component.css), width/height have fixed values.
On larger/smaller resolutions game container is bigger or smaller. It should be the same size on every device. If it can be made to look properly on mobile devices, will introduce controls for it also.

Here is how it currently looks like on mobile and tablet:

Mobile            |  Tablet
:-------------------------:|:-------------------------:
<img width="231" alt="mobile_example" src="https://user-images.githubusercontent.com/10077663/31074331-5da1e48e-a770-11e7-810c-ae38abaddb66.png"> |  <img width="242" alt="tablet_example" src="https://user-images.githubusercontent.com/10077663/31074332-5da36b60-a770-11e7-8a60-c9bb45f45b08.png">

**Comment by AntonyFenton** [comment]
Hey @SamirHodzic I'm also interested and will have a pop at it for you

**Comment by SamirHodzic** [comment]
Hey @AntonyFenton, sure, feel free to do it.

**Comment by AntonyFenton** [comment]
Hey @SamirHodzic Trying to push my changes but having Permission errors

**Comment by SamirHodzic** [comment]
You can't push directly. 
Make a fork of this repository, push changes to the new branch and make a pull request.
